baseURL = 'https://motes-played.post-self.ink/'
languageCode = 'en-us'
title = 'Motes Played'
theme = 'maddybook'
paginatePath = ""
disablePathToLower = true

[permalinks]
    post = '/:filename/'

[params]
    author = 'Madison Rye Progress and Samantha Yule Fireheart'
    home = 'https://makyo.ink/'
    copyright = '2024'
    subtitle = 'A Post-Self Story'
    subtitleLink = 'https://post-self.ink'
    customCSS = ['/css/motes-played.css']
    ogimg = '/square.png'

[markup.goldmark.renderer]
    unsafe = true
